//CREATE AN ARRAY FOR DATA ABOUT THE PRODUCTS
let productData = [
    {
        id: "prodPrincessRingsCollection",
        name: "Princess Rings Collection",
        price: 50,
        img: "images/productPhotos/princessRingsCollection.jpg",
        alt: "Princess Rings Collection of 5 rings",
    },
    {
        id: "prodPearlDaizeeCollection",
        name: "Pearl Daizee Collection",
        price: 50,
        img: "images/productPhotos/pearlDaizeeCollection.jpg",
        alt: "Pearl Daizee Collection of 5 rings",
    },
    {
        id: "prodFlowerGardenRingsCollection",
        name: "Flower Garden Rings Collection",
        price: 50,
        img: "images/productPhotos/flowerGardenRingsCollection.jpg",
        alt: "",
    },
    {
        id: "prodMiniGardenRingsCollection",
        name: "Mini Garden Rings Collection",
        price: 50,
        img: "images/productPhotos/miniGardenRingsCollection.jpg",
        alt: "Mini Garden Rings Collection of 2 rings",
    },
    {
        id: "prodMiniFloraCollection",
        name: "Mini Flora Collection",
        price: 50,
        img: "images/productPhotos/miniFloraCollection.jpg",
        alt: "Mini Flora Collection of 2 rings and 1 pair of earrings",
    },
    {
        id: "prodFloraRingsCollection",
        name: "Flora Rings Collection",
        price: 50,
        img: "images/productPhotos/floraRingsCollection.jpg",
        alt: "Flora Rings Collection of 4 rings",
    },
    {
        id: "prodGoldPearlsRingsCollection",
        name: "Gold Pearls Rings Collection",
        price: 50,
        img: "images/productPhotos/goldPearlsRingsCollection.jpg",
        alt: "Gold Pearls Rings Collection of 2 rings",
    },
    {
        id: "prodCherryRing",
        name: "Cherry Ring",
        price: 50,
        img: "images/productPhotos/cherryRing.jpg",
        alt: "Cherry ring",
    },
    {
        id: "prodPearlBowRing",
        name: "Pearl Bow Ring",
        price: 50,
        img: "images/productPhotos/pearlBowRing.jpg",
        alt: "Pearl bow ring",
    },
    {
        id: "prodPearlFlowerRing",
        name: "Pearl Flower Ring",
        price: 50,
        img: "images/productPhotos/pearlFlowerRing.jpg",
        alt: "Pearl Flower Ring",
    },
    {
        id: "prodPearlRing",
        name: "Pearl Ring",
        price: 50,
        img: "images/productPhotos/pearlRing.jpg",
        alt: "",
    },
    {
        id: "prodPeachChokerNecklace",
        name: "Peach Choker Necklace",
        price: 50,
        img: "images/productPhotos/peachChokerNecklace.jpg",
        alt: "Pearl Choker Necklace",
    },
];
